version: "3.8"

services:
  zotero-rdf:
    build: .
    container_name: zotero-rdf-server
    ports:
      - "${SERVER_PORT:-8000}:8000"
    env_file:
      - ./.env
    environment:
      - CONFIG_FILE
      - ZOTERO_CONFIG_FILE # =${ZOTERO_CONFIG_FILE:-zotero.yaml}
      - SERVER_PORT
    volumes:
      # - ./:/app           # dev mount
      - "${CONFIG_FILE:-config.yaml}:/app/${CONFIG_FILE:-config.yaml}"
      - "${ZOTERO_CONFIG_FILE:-zotero.yaml}:/app/${ZOTERO_CONFIG_FILE:-zotero.yaml}"
      - "${STORE_DIRECTORY:-./data}:/app/data"
      - "${EXPORT_DIRECTORY:-./exports}:/app/exports"
      - "${BACKUP_DIRECTORY:-./backup}:/app/backup"
      # - ${DB_PATH:-./users.db}:/app/users.db
    restart: unless-stopped
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    container_name: ${OXIGRAPH_CONTAINER}
    ports:
      - "7879:7879"
    volumes:
      - ${STORE_DIRECTORY:-./data}:/data
    command: ["serve-read-only", "--location", "/data", "--bind", "0.0.0.0:7879", "--union-default-graph", "--cors"]
    restart: unless-stopped