version: "3.8"

services:
  zotero-rdf:
    build: .
    container_name: ${ZOTERO_RDF_SERVER_CONTAINER}
    working_dir: /src
    command: uvicorn zotero_rdf_server.main:app --host 0.0.0.0 --port 8000
    ports:
      - "${SERVER_PORT:-8000}:8000"
    env_file:
      - ./.env
    volumes:
      - ./src:/src # dev (no reloading, though)
      - "${CONFIG_FILE_HOST:-./app/config.yaml}:${CONFIG_FILE:-/app/config.yaml}"
      - "${ZOTERO_CONFIG_FILE_HOST:-./app/zotero.yaml}:${ZOTERO_CONFIG_FILE:-/app/zotero.yaml}"
      - "${STORE_DIRECTORY:-./app/data}:/app/data"
      - "${PARSER_DIRECTORY:-./app/parser}:/app/parser"
      - "${EXPORT_DIRECTORY:-./app/exports}:/app/exports"
      - "${IMPORT_DIRECTORY:-./app/exports}:/app/import"
      - "${BACKUP_DIRECTORY:-./app/backup}:/app/backup"
    restart: unless-stopped
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    container_name: ${OXIGRAPH_CONTAINER}
    ports:
      - "7879:7879"
    volumes:
      - ${STORE_DIRECTORY:-./app/data}:/data
    command: ["serve-read-only", "--location", "/data", "--bind", "0.0.0.0:7879", "--union-default-graph", "--cors"]
    restart: unless-stopped