PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX zot:  <http://www.zotero.org/namespaces/export#>

SELECT ?file
       (SAMPLE(?date) AS ?date)
       (SAMPLE(?parent) AS ?parent)
       (SAMPLE(?parent_label) AS ?parent_label)
       (SAMPLE(?url) AS ?_input) # _input variable is required
       (GROUP_CONCAT(DISTINCT ?text_1724_9; SEPARATOR = "; ") AS ?parent_creators)
       (SAMPLE(?library) AS ?library)
       (SAMPLE(?library_label) AS ?library_label)
       (GROUP_CONCAT(DISTINCT ?text_1724_13; SEPARATOR = "; ") AS ?parent_tags)
       (SAMPLE(CONCAT(STR(?library_label), ":", STR(?_id))) AS ?_id) # _id variable is required
       (SAMPLE(?parent_key) AS ?parent_key)
       #(SAMPLE(?content) AS ?content)
       (SAMPLE(?file_label) AS ?file_label)
       (SAMPLE(?link_type) AS ?link_type)
WHERE {
  ?file a zot:attachment;
        zot:key ?_id;
        zot:linkMode ?link_type;
        rdfs:label ?file_label;
        zot:parentItem ?parent.

VALUES ?link_type { "linked_url" "imported_url" }. # filter on attachment types
    
OPTIONAL { ?parent rdfs:label ?parent_label }
OPTIONAL { ?parent zot:date ?date }
OPTIONAL { ?parent zot:key ?parent_key }
OPTIONAL { ?parent (zot:creators/zot:hasCreator) ?person_1742_8. }

OPTIONAL {  ?person_1742_8 rdf:type zot:actor;
                           rdfs:label ?text_1724_9.  }

OPTIONAL {  ?file zot:url ?url;
                  zot:inLibrary ?library.}
  
OPTIONAL {  ?library rdf:type zot:library;
                     zot:id ?library_label.}

# FILTER( # filter on attachment name
#     CONTAINS(?file_label, "PDF") #||
# #    CONTAINS(?file_label, "Books")
#   )

# FILTER( # filter on attachment URL
#     CONTAINS(STR(?url), "archive") 
#   )

  ?file zot:tags ?t . # ?t_ingest, ?t_pdf .

#  ?t_ingest a zot:tag ; zot:tag "*ingest" .
#  ?t_pdf    a zot:tag ; zot:tag "*pdf" .
  ?t a zot:tag ;
     zot:tag ?tagVal .

  VALUES ?tagVal { "*pdf" "*iiif" }.

  OPTIONAL {
    ?parent zot:tags ?tag_1502_13.
    ?tag_1502_13 rdf:type zot:tag;
                 zot:tag ?text_1724_13.
  }
}
GROUP BY ?file
# LIMIT 1