PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX zot:  <http://www.zotero.org/namespaces/export#>

SELECT ?file
       (SAMPLE(?date) AS ?date)
       (SAMPLE(?parent) AS ?parent)
       (SAMPLE(?parent_label) AS ?_label) # _label variable is optional
       (SAMPLE(?parent_label) AS ?parent_label)
       (SAMPLE(?parent_title) AS ?parent_title)
       (SAMPLE(?url) AS ?_input) # _input variable is required
       (GROUP_CONCAT(DISTINCT ?text_1724_9; SEPARATOR = "; ") AS ?parent_creators)
       (SAMPLE(?library) AS ?library)
       (SAMPLE(?library_label) AS ?library_label)
       (GROUP_CONCAT(DISTINCT ?text_1724_13; SEPARATOR = "; ") AS ?parent_tags)
       (SAMPLE(CONCAT(STR(?library_label), ":", STR(?_id))) AS ?_id) # _id variable is required
       (SAMPLE(?parent_key) AS ?parent_key)
       #(SAMPLE(?content) AS ?content)
       (SAMPLE(?file_label) AS ?file_label)
       (SAMPLE(?link_type) AS ?link_type)
WHERE {
  ?file a zot:attachment;
        zot:key ?_id;
        zot:linkMode ?link_type;
        rdfs:label ?file_label;
        zot:parentItem ?parent.

VALUES ?link_type { "linked_url" "imported_url" }. # filter on attachment types
    
OPTIONAL { ?parent rdfs:label ?parent_label }
OPTIONAL { ?parent zot:date ?date }
OPTIONAL { ?parent zot:title ?parent_title }
OPTIONAL { ?parent zot:key ?parent_key }

OPTIONAL {
  ?parent (zot:creators/zot:hasCreator) ?person_1742_8 .
  ?person_1742_8 a zot:actor ;
                 rdfs:label ?text_1724_9 .
}


OPTIONAL {  ?file zot:url ?url;
                  zot:inLibrary ?library.}
  
OPTIONAL {  ?library rdf:type zot:library;
                     zot:id ?library_label.}

  ?file zot:tags ?t_format .
  ?t_format a zot:tag ;
            zot:tag ?formatTag .
  VALUES ?formatTag { "*pdf" "*iiif" }

  FILTER NOT EXISTS {
    ?file zot:tags ?redoTag .
    ?redoTag a zot:tag ;
            zot:tag "**redo_OCR" .
  }
  
  # FILTER(CONTAINS(STR(?url), "uni-halle.de")) # filter on attachment URL api.onb.ac.at poor quality
  # FILTER(CONTAINS(STR(?file), "SU8DGT98")) # filter on attachment URL
  # FILTER(
  #   REGEX(STR(?_id), "747CPE5P|K4S8F6G3|9DDYJWFS|A3NGVGDY|R8GLPVX7|IUP5G5Z9|ZI2DXZBB")
  # )
  ?parent zot:collections <https://zotero.org/groups/4929619/collections/9D9XX2VG> . # Filter pending

  OPTIONAL {
    ?parent zot:tags ?tag_1502_13.
    ?tag_1502_13 rdf:type zot:tag;
                 zot:tag ?text_1724_13.
  }
}
GROUP BY ?file
ORDER BY ?_input
# OFFSET 5
# LIMIT 3