PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX zot:  <http://www.zotero.org/namespaces/export#>

SELECT
  ?file
  (SAMPLE(?raw_date) AS ?date)
  (YEAR(SAMPLE(?raw_date)) AS ?year)
  (SAMPLE(?raw_parent) AS ?parent)
  (SAMPLE(?raw_parent_label) AS ?_label)
  (SAMPLE(?raw_parent_label) AS ?parent_label)
  (SAMPLE(?raw_language) AS ?language)
  (SAMPLE(?raw_parent_title) AS ?parent_title)
  (SAMPLE(?raw_url) AS ?_input)
  (
    GROUP_CONCAT(
      DISTINCT ?creator_label;
      SEPARATOR = "; "
    )
    AS ?parent_creators
  )
  (SAMPLE(?raw_library) AS ?library)
  (SAMPLE(?raw_library_label) AS ?library_label)
  (
    GROUP_CONCAT(
      DISTINCT ?tag_label;
      SEPARATOR = "; "
    )
    AS ?parent_tags
  )
  (
    GROUP_CONCAT(
      DISTINCT ?collection_label;
      SEPARATOR = "; "
    )
    AS ?collection_labels
  )
  (
    SAMPLE(
      CONCAT(
        STR(?library_id),
        ":",
        STR(?attachment_id)
      )
    )
    AS ?_id
  )
  (SAMPLE(?raw_parent_key) AS ?parent_key)
  (SAMPLE(?raw_file_label) AS ?file_label)
  (SAMPLE(?raw_link_type) AS ?link_type)

WHERE {
  ?file
    a zot:Attachment ;
    zot:key ?attachment_id ;
    zot:linkMode ?raw_link_type ;
    rdfs:label ?raw_file_label ;
    zot:parentItem ?raw_parent .

  FILTER(
    STR(?raw_link_type) IN (
      "linked_url",
      "imported_url"
    )
  )

  OPTIONAL {
    ?raw_parent rdfs:label ?raw_parent_label .
  }

  OPTIONAL {
    ?raw_parent zot:language/rdfs:label ?raw_language .
  }

  OPTIONAL {
    ?raw_parent zot:date ?raw_date .
  }

  OPTIONAL {
    ?raw_parent zot:title ?raw_parent_title .
  }

  OPTIONAL {
    ?raw_parent zot:key ?raw_parent_key .
  }

  OPTIONAL {
    ?raw_parent zot:collections/zot:name ?collection_label .
  }

  OPTIONAL {
    ?raw_parent zot:creators/zot:hasCreator ?creator .

    ?creator
      a zot:Agent ;
      rdfs:label ?creator_label .
  }

  OPTIONAL {
    ?file
      zot:url ?raw_url ;
      zot:inLibrary ?raw_library .
  }

  OPTIONAL {
    ?raw_library
      rdf:type zot:Library ;
      rdfs:label ?raw_library_label ;
      zot:id ?library_id .
  }

  OPTIONAL {
    ?raw_parent zot:tags ?tag .

    ?tag
      rdf:type zot:Tag ;
      zot:tag ?tag_label .
  }

}

GROUP BY ?file
ORDER BY ?_input

# OFFSET 50
# LIMIT 50